name: Build, test, format and lint

on:
  push:
  pull_request:

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    name: Build binary for ${{ matrix.platform.name }}
    strategy:
      matrix:
        platform:
        - name: linux on amd64
          task: build-linux-amd64
        - name: linux on arm64
          task: build-linux-arm64
        - name: osx on amd64
          task: build-darwin-amd64
        - name: osx on arm64
          task: build-darwin-arm64
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Build binaries
        run: make ${{ matrix.platform.task }}

  format-lint:
    runs-on: ubuntu-latest
    name: Format and lint
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Install tools
        run: make install-tools

      - name: Format
        run: make fmt && git diff --quiet

      - name: Lint
        run: make lint

  e2e-test:
    runs-on: ubuntu-latest
    name: E2E Test
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Run e2e test
        run: make e2e-tests

  unit-tests:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Run unit test
        run: make test

  integration-tests:
    runs-on: ubuntu-latest
    name: Integration tests
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Setup database
        run: docker run --rm -d -p9000:9000 --name test-clickhouse-server --ulimit nofile=262144:262144 clickhouse/clickhouse-server:22

      - name: Run integration tests
        run: make integration-test
