name: Release

on:
  push:
    tags: ['[0-9]+\.[0-9]+\.[0-9]+']

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Create release distribution
        run: make build-all-platforms tar-all-platforms

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: |
          export DOCKER_TAG=${GITHUB_REF##*/}
          make docker docker-push

      - name: Create Github release
        run: |
          export TAG=${GITHUB_REF##*/}
          gh release create ${TAG} --title "Release ${TAG}" *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
