name: Test my actions

on:
  push:
  pull_request:

jobs:
  example-run:
    runs-on: ubuntu-latest
    name: Example run
    steps:
      - uses: pavolloffay/github-actions/helloworld-composite/@main
        with:
          inputString: John Doe
